theme: jekyll-theme-Slate
# theme: jekyll-theme-minimal
title: 池田研究室
description: 龍谷大学先端理工学部知能情報メディア課程
date: 2024-11-11 18:29:00
Navigation:
- title: Home
- url: /index.html
- title: About
  url: http://xociety.co
- title: Contact
  url: /contact
